name       : lollypop
version    : 0.9.72
release    : 15
source     :
    - https://github.com/gnumdk/lollypop/archive/0.9.72.tar.gz : 04df91a24fba2da8e9bef5c4928f77698e581bf689d371fa56c6259652f9751f
license    : GPL-3.0
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - pkgconfig(gobject-introspection-1.0) 
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(totem-plparser)
    - itstool
    - intltool
    - python3-dbus
    - python3-pylast
rundeps: 
    - python-requests
    - python-beautifulsoup4
    - python-six
    - python-wikipedia
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - totem-pl-parser
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
