name       : lollypop
version    : 0.9.206
release    : 52
source     :
    - https://github.com/gnumdk/lollypop/archive/0.9.206.tar.gz : 86e24c9a03867988026bf1f2b16714c7d464945ddb2666fb351393a8072d2a88
license    : GPL-3.0
component  : multimedia.audio
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - intltool
    - itstool
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(totem-plparser)
    - python3-dbus
    - python3-pylast
rundeps    :
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-requests
    - python-six
    - python-wikipedia
    - totem-pl-parser
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
