name       : lollypop
version    : 1.2.16
release    : 126
source     :
    - https://gitlab.gnome.org/World/lollypop/uploads/70aab11cf17a8966a5bb188b4173b240/lollypop-1.2.16.tar.xz : 31d5e56116149c80d6dfc7fbd8bb3d92b0c5e337ea5d4688618f23f6cfd8e8a6
license    :
    - CC0-1.0
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a modern music player for GNOME.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(totem-plparser)
    - itstool
rundeps    :
    - python3-cairo
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-pillow
    - python-requests
    - python-six
    - totem-pl-parser
    - youtube-dl
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
