name       : lollypop
version    : 0.9.237
release    : 76
source     :
    - https://github.com/gnumdk/lollypop/releases/download/0.9.237/lollypop-0.9.237.tar.xz : 461f7710ecacfa4bd09efc8ec4f52955b9d327a08704fbed3a316b48fa2df508
license    : GPL-3.0
component  : multimedia.audio
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(totem-plparser)
    - git
    - intltool
    - itstool
    - python3-dbus
    - python3-pylast
rundeps    :
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-requests
    - python-six
    - python-wikipedia
    - totem-pl-parser
setup      : |
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
