name       : lollypop
version    : 0.9.240
release    : 79
source     :
    - https://github.com/gnumdk/lollypop/releases/download/0.9.240/lollypop-0.9.240.tar.xz : 78cbd57c41f5d97f8c9286f7e01c0c3d0fde17a3dc01a4a5bae1bf665e653e58
license    : GPL-3.0
component  : multimedia.audio
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(totem-plparser)
    - git
    - intltool
    - itstool
    - python3-dbus
    - python3-pylast
rundeps    :
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-requests
    - python-six
    - python-wikipedia
    - totem-pl-parser
setup      : |
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
