name       : lollypop
version    : 0.9.31
release    : 1
source     :
    - https://github.com/gnumdk/lollypop/releases/download/0.9.31/lollypop-0.9.31.tar.xz : bef1d0e87ac941dc471d8a1e658feb3254f1e76da4b69f8cbe754aa8bcdb9c79
license    : GPL-3.0
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(py3cairo)
    - pkgconfig(totem-plparser)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(dbus-python)
    - desktop-file-utils
    - itstool
    - python3-pylast
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
