name       : lollypop
version    : 0.9.51
release    : 6
source     :
    - https://github.com/gnumdk/lollypop/releases/download/0.9.51/lollypop-0.9.51.tar.xz : a814f645b177f68e6003526757ea10fd4be15ab99530d0eab30713ffc486d0d2
license    : GPL-3.0
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - pkgconfig(gobject-introspection-1.0) 
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(totem-plparser)
    - itstool
    - intltool
    - python3-dbus
    - python3-pylast
rundeps: 
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - totem-pl-parser
setup      : |
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
