name       : lollypop
version    : 0.9.214
release    : 57
source     :
    - https://github.com/gnumdk/lollypop/archive/0.9.214.tar.gz : c5c5a39ab9bdf43ae8ee0fd8536e4eee7a303ea94653c9d9b7253500f4fb9aa9
license    : GPL-3.0
component  : multimedia.audio
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - intltool
    - itstool
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(totem-plparser)
    - python3-dbus
    - python3-pylast
rundeps    :
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-requests
    - python-six
    - python-wikipedia
    - totem-pl-parser
setup      : |
    %autogen --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
