name       : lollypop
version    : 0.9.61
release    : 9
source     :
    - https://github.com/gnumdk/lollypop/archive/0.9.61.tar.gz : 0360faeb5507f22a3230cbda6f97d48726fd15b84c9ae3a85aed46b14c6826bc
license    : GPL-3.0
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - pkgconfig(gobject-introspection-1.0) 
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(totem-plparser)
    - itstool
    - intltool
    - python3-dbus
    - python3-pylast
rundeps: 
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - totem-pl-parser
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
