name       : lollypop
version    : 0.9.103
release    : 36
source     :
    - https://github.com/gnumdk/lollypop/archive/0.9.103.tar.gz : b0c97ae67d38a382c29170992b9c905e9054b9795ea8412fea92becc601624ef
license    : GPL-3.0
component  : desktop.multimedia
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a new GNOME music playing application
builddeps  :
    - intltool
    - itstool
    - pkgconfig(gobject-introspection-1.0) 
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(totem-plparser)
    - python3-dbus
    - python3-pylast
rundeps: 
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-requests
    - python-six
    - python-wikipedia
    - totem-pl-parser
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
