name       : lollypop
version    : 0.9.924
release    : 100
source     :
    - git|https://gitlab.gnome.org/gnumdk/lollypop.git : 0.9.924
license    :
    - CC0-1.0
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Lollypop is a new GNOME music playing application
description: |
    Lollypop is a modern music player for GNOME.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(totem-plparser)
    - git
    - itstool
rundeps    :
    - python3-cairo
    - python3-gobject
    - python3-pylast
    - python-beautifulsoup4
    - python-pillow
    - python-requests
    - python-six
    - python-wikipedia
    - totem-pl-parser
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
