name       : lollypop
version    : 1.4.34
release    : 155
source     :
    - git|https://gitlab.gnome.org/World/lollypop.git : 1.4.34
homepage   : https://wiki.gnome.org/Apps/Lollypop
license    :
    - CC0-1.0
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Lollypop is a modern GNOME music playing application
description: |
    Lollypop is a modern music player for GNOME.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(totem-plparser)
    - itstool
rundeps    :
    - libhandy
    - python3-cairo
    - python3-pylast
    - python-beautifulsoup4
    - python-gobject
    - python-pillow
    - python-requests
    - python-six
    - totem-pl-parser
    - yt-dlp
setup      : |
    %patch -p1 < $pkgfiles/0001-Replace-youtube-dl-with-yt-dlp.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
